            - name: Attest Build Provenance
  uses: actions/attest-build-provenance@v2.2.0
  with:
    # Path to the artifact serving as the subject of the attestation. Must specify exactly one of "subject-path", "subject-digest", or "subject-checksums". May contain a glob pattern or list of paths (total subject count cannot exceed 1024).

    subject-path: # optional
    # Digest of the subject for which provenance will be generated. Must be in the form "algorithm:hex_digest" (e.g. "sha256:abc123..."). Must specify exactly one of "subject-path", "subject-digest", or "subject-checksums".

    subject-digest: # optional
    # Subject name as it should appear in the attestation. Required when identifying the subject with the "subject-digest" input.

    subject-name: # optional
    # Path to checksums file containing digest and name of subjects for attestation. Must specify exactly one of "subject-path", "subject-digest", or "subject-checksums".

    subject-checksums: # optional
    # Whether to push the provenance statement to the image registry. Requires that the "subject-name" parameter specify the fully-qualified image name and that the "subject-digest" parameter be specified. Defaults to false.

    push-to-registry: # optional
    # Whether to attach a list of generated attestations to the workflow run summary page. Defaults to true.

    show-summary: # optional, default is true
    # The GitHub token used to make authenticated API requests.

    github-token: # optional, default is ${{ github.token }}
          
